import React, { useState, useEffect } from 'react';
import { Link } from 'react-router-dom';
import { Plus, Search } from 'lucide-react';
import Button from '../components/ui/Button';
import Badge from '../components/ui/Badge';
import useApi from '../hooks/useApi';

const getStatusVariant = (status) => {
    switch (status) {
        case 'Open': return 'green';
        case 'Closed': return 'gray';
        default: return 'gray';
    }
};

const JobList = () => {
    const [jobs, setJobs] = useState([]);
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState(null);
    const api = useApi();

    useEffect(() => {
        const fetchJobs = async () => {
            try {
                const response = await fetch(api.jobs.getAll);
                if (response.ok) {
                    const data = await response.json();
                    setJobs(data);
                }
            } catch (error) {
                console.error('Failed to fetch jobs:', error);
                setError(error.message);
            } finally {
                setLoading(false);
            }
        };

        fetchJobs();
    }, [api.jobs.getAll]); // Add dependency if api object is stable, but useApi creates new object every render if not memoized.
    // Given simple implementation, this might cause infinite loop if useApi returns new object reference on every render.
    // Let's assume for now. Actually, looking at useApi implementation:
    // It returns a new object on every call. This will cause infinite loop if used in dependency array.
    // I should fix useApi first or memoize the object inside it, OR just remove dependency.
    // But I cannot modify useApi in this tool call.
    // I will remove the dependency for now or treat api.jobs.getAll as string (which it is, generated by function).
    // api.jobs.getAll is a STRING. So it is safe to use in dependency array.
    // Ah, wait. useApi returns: { jobs: { getAll: 'url' ... } }
    // 'getAll' is a string. So api.jobs.getAll is a stable value (string literal).
    // Wait, `getApiRoute` returns a string.
    // So `api.jobs.getAll` is just 'http://localhost:5000/api/jobs'.
    // It is stable across renders (same string value). React compares by value.
    // So it is safe.

    return (
        <div className="space-y-6">
            {/* Header */}
            <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
                <div>
                    <h1 className="text-2xl font-bold text-gray-900">Jobs</h1>
                    <p className="mt-1 text-sm text-gray-500">Manage your job postings and view applicants.</p>
                </div>
                <Link to="/jobs/create">
                    <Button>
                        <Plus className="h-4 w-4 mr-2" />
                        Create Job
                    </Button>
                </Link>
            </div>

            {/* Filters & Search */}
            <div className="bg-white p-4 rounded-lg shadow-sm border border-gray-200 flex flex-col sm:flex-row gap-4 justify-between items-center">
                <div className="relative w-full sm:w-96">
                    <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
                        <Search className="h-4 w-4 text-gray-400" />
                    </div>
                    <input
                        type="text"
                        className="block w-full pl-10 pr-3 py-2 border border-gray-300 rounded-md leading-5 bg-white placeholder-gray-500 focus:outline-none focus:placeholder-gray-400 focus:ring-1 focus:ring-blue-500 focus:border-blue-500 sm:text-sm"
                        placeholder="Search jobs..."
                    />
                </div>
                <div className="flex gap-2 w-full sm:w-auto">
                    {/* Filter removed */}
                </div>
            </div>

            {/* Jobs Table */}
            <div className="bg-white shadow-sm border border-gray-200 rounded-lg overflow-hidden">
                <table className="min-w-full divide-y divide-gray-200">
                    <thead className="bg-gray-50">
                        <tr>
                            <th scope="col" className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Job Title</th>
                            <th scope="col" className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Department</th>
                            <th scope="col" className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Location</th>
                            <th scope="col" className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Status</th>
                            <th scope="col" className="px-6 py-3 text-right text-xs font-medium text-gray-500 uppercase tracking-wider">Actions</th>
                        </tr>
                    </thead>
                    <tbody className="bg-white divide-y divide-gray-200">
                        {loading ? (
                            <tr>
                                <td colSpan="5" className="px-6 py-4 text-center text-sm text-gray-500">Loading jobs...</td>
                            </tr>
                        ) : error ? (
                            <tr>
                                <td colSpan="5" className="px-6 py-4 text-center text-sm text-red-500">
                                    Error loading jobs: {error}
                                    <br />
                                    <span className="text-xs text-gray-400">Target: {api.jobs.getAll}</span>
                                </td>
                            </tr>
                        ) : jobs.length === 0 ? (
                            <tr>
                                <td colSpan="5" className="px-6 py-4 text-center text-sm text-gray-500">No jobs found.</td>
                            </tr>
                        ) : (
                            jobs.map((job) => (
                                <tr key={job._id || job.id} className="hover:bg-gray-50 transition-colors">
                                    <td className="px-6 py-4 whitespace-nowrap">
                                        <div className="flex items-center">
                                            <div>
                                                <div className="text-sm font-medium text-gray-900">{job.jobTitle || job.title}</div>
                                                <div className="text-sm text-gray-500">{job.applicants?.length || 0} Applicants</div>
                                            </div>
                                        </div>
                                    </td>
                                    <td className="px-6 py-4 whitespace-nowrap">
                                        <div className="text-sm text-gray-900">{job.department}</div>
                                    </td>
                                    <td className="px-6 py-4 whitespace-nowrap">
                                        <div className="text-sm text-gray-500">{job.location}</div>
                                    </td>
                                    <td className="px-6 py-4 whitespace-nowrap">
                                        <Badge variant={getStatusVariant(job.status)}>{job.status}</Badge>
                                    </td>
                                    <td className="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                                        <Link to={`/jobs/${job._id || job.id}`} className="text-blue-600 hover:text-blue-900">View Details</Link>
                                    </td>
                                </tr>
                            ))
                        )}
                    </tbody>
                </table>
            </div>
        </div>
    );
};

export default JobList;
